name: Deploy Docs

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: s
        run: |
          export PYTHONPATH="${pwd}:$PYTHONPATH"
          export PYTHONPATH="${pwd}/athenaSQL:$PYTHONPATH"
          
      - name: Set up Python 3.9
        run: python -c "import sys
          print(sys.path)"
